### ISSUE TITLE
Oscar Sousa error index

### ISSUE THREAD

**Issue by Sebasescolesnuria** [OLaita/todoM8#2]
@Sousa2001 
Oscar, he encontrado un error en el índex que has modificado tu, necesito que lo modifiques para que mi parte funcione correctamente.
![Screenshot_1](https://user-images.githubusercontent.com/73191372/115733467-37fb5f80-a389-11eb-944e-9721b6f74016.png)

**Comment by Sousa2001** [comment]
Corrección realizada, probad ahora a ver si os funciona
