### ISSUE TITLE
Sebas error template

### ISSUE THREAD

**Issue by Pablogl01** [OLaita/todoM8#3]
@Sebasescolesnuria 
Sebas, he podido ver que no has des comentado una parte de template.php. ¿Puedes arreglarlo? me esta dando conflictos.

![image](https://user-images.githubusercontent.com/31620595/115733384-231ecc00-a389-11eb-90c7-eb15df65ab0d.png)

**Comment by Sebasescolesnuria** [comment]
Templates solucionadas, perdón por la tardanza
